import type { MusicMoodId } from '@/lib/music-moods'
import type { Language } from '@/lib/translations'

export type DjPresetLocale = 'en' | 'zh'

/** Fixed immersive scripts — no dynamic timestamps so TTS cache keys stay stable. */
export const DJ_PRESET_LINES: Record<MusicMoodId, Record<DjPresetLocale, readonly string[]>> = {
  'neon-tokyo': {
    en: [
      'Captain, welcome to Neon Tokyo. Millions sleep below, but our cyber night is just waking up. Lock onto the frequency and let the synth rain wash the day away.',
      'This is the underground rebel channel. The city hums like a dying star, and we are the ones still awake. Plug in, Captain — the night shift belongs to us.',
      'Neon bleeds into wet asphalt out there. In here, only basslines and focus. Random frequency locked. Let the electric tide carry you deeper.',
      'Captain, the rooftop antennas are singing. Somewhere a million screens flicker, but this cockpit is yours alone. Cyber midnight starts now.',
      'They closed the clubs hours ago. We opened a secret wavelength instead. Welcome back to the resistance frequency, Captain.',
      'Rain on glass, violet signs, distant trains. I have tuned the deck to pure retrowave. Breathe in the neon and exhale the noise.',
      'Captain, the grid never sleeps — neither do we. Your signal is clean. The rebel broadcast is live and the night is long.',
      'Static clears… and there you are. Neon Tokyo welcomes its captain. Let the dark synth pulse rewrite your rhythm.',
      'The megacity dreams in LED. We dream in code and kick drums. Frequency locked. Ride the wave until sunrise blinks.',
      'Captain, I saved you a seat at the edge of the skyline. The bass is low, the air is cool, and the cyber night is infinite.',
      'Pirate signal online. Official channels are boring tonight. Stay with me — the underground always sounds better after midnight.',
      'Neon fog rolling in. Your cockpit lights match the street below. Tune in, drop out of the ordinary, and focus.',
      'Captain, welcome aboard the midnight express. Next stop: deep flow state. All departures are imaginary; all arrivals are real.',
      'The city whispers gossip through power lines. We answer with synthesizers. Lock the frequency and disappear into the glow.',
      'You made it through the surface noise. Down here it is just you, me, and a perfect wave of electric calm.',
      'Captain, the rebellion is quiet tonight — just headphones and heartbeats. Neon Tokyo is open for business until dawn.',
      'Skyline glitter, subwoofer thunder, coffee gone cold. Perfect conditions. Let us finish what the day could not.',
      'Random access granted. The deck is hot, the night is young, and the only rule is: stay in the groove.',
      'Captain, the rain stopped but the neon did not. I am keeping the signal warm. Step into the cyber dark with me.',
      'Last call on the surface world. First call in the underground. Welcome back, Captain — the night frequency is yours.',
    ],
    zh: [
      '艦長，歡迎來到霓虹東京。腳下上千萬人早已入睡，我們的賽博深夜才剛甦醒。鎖定頻率，讓合成器細雨把白日的雜訊沖走。',
      '這裡是地下電台反抗軍頻道。城市像瀕死的恆星低鳴，只有我們還醒著。接入吧，艦長，夜班屬於我們。',
      '霓虹在濕瀝青上暈開，艙內只剩低音與專注。隨機調頻已鎖定，讓電子潮汐帶你更深。',
      '艦長，天台天線在唱歌。百萬螢幕閃爍，但這駕駛艙只屬於你。賽博午夜，現在開始。',
      '地上的俱樂部早已打烊，我們改開一條秘密波長。歡迎回到反抗軍頻率，艦長。',
      '玻璃上的雨、紫色招牌、遠處的列車。我已把轉盤調到純合成波。吸入霓虹，呼出噪音。',
      '艦長，電網從不睡眠，我們也不。你的信號乾淨清晰。反抗廣播已上線，夜還很長。',
      '雜訊清除，你來了。霓虹東京歡迎它的艦長。讓暗色合成脈衝重寫你的節奏。',
      '巨城在 LED 裡做夢，我們在程式碼與底鼓裡做夢。頻率鎖定，騎浪直到日出。',
      '艦長，我在天際線邊緣為你留了座位。低音沉沉，空氣清涼，賽博之夜沒有盡頭。',
      '盜版信號上線。官方頻道今晚無聊。留在我身邊，地下永遠比午夜之後更好聽。',
      '霓虹霧正在湧來。你的駕駛艙燈光與腳下街道呼應。調頻，脫離日常，進入專注。',
      '艦長，歡迎登上午夜特快。下一站是心流深處。所有出發都是想像，所有抵達都真實。',
      '城市透過電線竊竊私語，我們用合成器回答。鎖定頻率，消失在这片光裡。',
      '你穿過了地表的噪音。在這裡只有你、我，和一道完美的電子寧靜。',
      '艦長，今晚的反抗很安靜，只有耳機與心跳。霓虹東京營業至黎明。',
      '天際線閃光、低音雷鳴、咖啡已涼。完美條件。來完成白天完不成的事。',
      '隨機存取已授權。轉盤正熱，夜還年輕，唯一規則是留在節奏裡。',
      '艦長，雨停了但霓虹沒有。我會保持信號溫暖。與我一起走進賽博暗處。',
      '地表世界最後呼叫。地下世界第一次呼叫。歡迎回來，艦長，夜間頻率屬於你。',
    ],
  },
  'deep-night': {
    en: [
      'Captain, Houston reads you loud and clear. Deep space is quiet tonight — surface noise fully isolated. Coffee optional; focus mandatory.',
      'This is mission control on the late shift. The station drifts in silence and so should your mind. You are cleared for deep work.',
      'Captain, orbital telemetry is calm. No alerts, no turbulence — just you and the infinite dark beyond the window.',
      'Ground to cockpit: all systems nominal. The universe is holding its breath. Settle in and let the quiet do its job.',
      'Captain, I have dimmed the console to starship midnight. Your only mission tonight is presence.',
      'Deep night protocol engaged. Atmospheric interference zero. The channel is clean — proceed to focus vector.',
      'Captain, the ISS observation deck is empty except for you. Earth glows softly below. Breathe once, begin.',
      'Houston here. We have a go for uninterrupted flow. The night belongs to careful, unhurried thought.',
      'Captain, cosmic background hum detected — perfectly normal, perfectly soothing. Lock in and drift.',
      'Surface world is offline for you now. Up here, only stars and task lists. Houston stands by.',
      'Captain, telemetry whispers: you are exactly where you need to be. The deep night welcomes its captain.',
      'Mission log: silence achieved. Cognitive shields up. You are cleared to enter the work zone.',
      'Captain, the dark side of the orbit is peaceful. Use this hour like a precious oxygen reserve.',
      'Ground control sees your signal steady. No distractions on radar. Proceed with calm authority.',
      'Captain, deep night is not empty — it is full of room to think. Houston is listening.',
      'Orbital night cycle active. External comms muted. Internal focus amplified. Begin when ready.',
      'Captain, the void is not hostile tonight. It is a blanket. Pull it over your shoulders and work.',
      'Houston confirms: all noise gates closed. Only the gentle hum of disciplined concentration remains.',
      'Captain, you have slipstream clearance through midnight. The cosmos is patient; so am I.',
      'Final check complete. Oxygen good, mood stable, frequency locked on stillness. Welcome to deep night, Captain.',
    ],
    zh: [
      '艦長，休斯頓聽見你，信號清晰。深邃宇宙今夜很安靜——地表噪音已完全隔離。咖啡可選，專注必備。',
      '這是任務控制中心的深夜班。空間站靜靜飄移，你的思緒也該如此。你已獲准進入深度工作。',
      '艦長，軌道遙測平穩。無警報、無亂流——只有你和舷窗外無尽的黑暗。',
      '地面呼叫駕駛艙：所有系統正常。宇宙正屏息。安頓下來，讓寧靜發揮作用。',
      '艦長，我已把控制台調到星艦午夜模式。你今晚唯一的任務是：在场。',
      '深夜協議已啟動。大氣干擾為零。頻道干净——請進入心流向量。',
      '艦長，國際太空站觀景台空無一人，只有你。地球在下方柔和發光。呼吸一次，開始吧。',
      '休斯頓呼叫。准许不间断心流。这个夜晚属于细致、从容的思考。',
      '艦長，检测到宇宙背景嗡鸣——完全正常，完全治愈。锁定，漂浮。',
      '地表世界已为你下线。在这里，只有星辰与待办。休斯頓待命。',
      '艦長，遙測低語：你就在该在的位置。深夜宇宙欢迎它的舰长。',
      '任務日誌：寂静达成。认知护盾升起。准许进入工作区。',
      '艦長，轨道暗面很和平。把这一个小时当作珍贵的氧气储备来用。',
      '地面控制看见你的信号稳定。雷达无干扰。以 calm 的权威继续。',
      '艦長，深夜不是空——它充满思考的空间。休斯頓在听。',
      '軌道夜間循環啟動。外部通讯静音。内部专注放大。准备好了就开始。',
      '艦長，今晚的虚空并不 hostile——它是一条毯。披上它，工作吧。',
      '休斯頓确认：所有 noise gate 已关。只剩 disciplined 专注的 gentle 嗡鸣。',
      '艦長，你已获得午夜 slipstream 通行许可。宇宙有耐心；我也是。',
      '最終檢查完成。氧气良好、状态稳定、频率锁定在静止。欢迎进入深夜宇宙，艦長。',
    ],
  },
  'deep-space': {
    en: [
      'Captain, depth three thousand feet. External noise nullified. Drone frequency engaged for maximum focus.',
      'Submarine mode steady. Hull integrity one hundred percent. Proceed in silence.',
      'Captain, sonar reports zero surface interference. The deep is yours.',
      'Pressure stable. Oxygen nominal. Cognitive dampeners online. Begin descent into work.',
      'Captain, the ocean above is loud; the cabin below is not. Stay with the low frequency.',
      'Depth check complete. All ambient channels sealed. Only task signal remains.',
      'Captain, rational mode active. Emotion minimized, clarity maximized. Continue.',
      'The abyss is quiet by design. You are safe to think here.',
      'Captain, passive acoustic shield holding. No distractions penetrate this depth.',
      'Telemetry: heartbeat slow, mind sharp. Optimal conditions detected.',
      'Captain, the drone zone is not empty — it is precise. Align with the hum.',
      'External world logged out. Internal systems prioritized. Acknowledge and proceed.',
      'Captain, depth holding. Time dilates down here. Use it.',
      'Noise floor at minimum. Signal-to-focus ratio optimal. You are cleared.',
      'Captain, submarine AI reporting: all calm. The deep night of the mind welcomes you.',
      'Pressure outside increases; pressure inside releases. Breathe once. Work.',
      'Captain, long-wave ambient locked. Surface alerts cannot reach you.',
      'Hull sensors clean. Thought sensors cleaner. Maintain course on current task.',
      'Captain, the deep does not hurry. Neither should you. Steady progress only.',
      'End of surface transmission. Deep-space low hum is now your only companion.',
    ],
    zh: [
      '艦長，深度三千呎。外部雜音已消除。深空低鳴頻率已接入，專注最大化。',
      '潛艇模式穩定。船殼完整性百分之百。在寂靜中繼續。',
      '艦長，聲納回報零地表干擾。深海属于你。',
      '壓力穩定。氧氣正常。認知阻尼上線。開始下潛至工作深度。',
      '艦長，上方海洋喧囂；下方艙內不然。留在低頻裡。',
      '深度檢查完成。所有環境頻道已密封。只剩任務信號。',
      '艦長，理性模式啟動。情緒最小化，清晰度最大化。繼續。',
      '深淵的安靜是設計好的。你可以在這裡安全思考。',
      '艦長，被動聲學護盾維持中。沒有干擾能穿透這個深度。',
      '遙測：心跳緩慢，思緒敏銳。最佳條件已檢測。',
      '艦長，低鳴區並非空虛——它很精準。與嗡鳴對齊。',
      '外部世界已登出。內部系統優先。確認並繼續。',
      '艦長，深度保持。時間在此稀釋。善用它。',
      '噪聲底限最低。信噪比最佳。你已獲准。',
      '艦長，潛艇 AI 回報：一切平靜。心智的深夜歡迎你。',
      '外部壓力上升；內部壓力釋放。呼吸一次。工作。',
      '艦長，長波環境鎖定。地表警報無法抵達。',
      '船殼感測器干净。思緒感測器更干净。保持當前任務航向。',
      '艦長，深海從不匆忙。你也不必。只要穩定前進。',
      '地表傳輸結束。深空低鳴是你唯一的同伴。',
    ],
  },
  'galactic-tavern': {
    en: [
      'Captain, come in from the cold. The bar is warm, the lights are low, and the first note is already waiting for you.',
      'Hey, old friend. Rough day out there? Leave it on the coat rack. I poured you something smooth.',
      'Captain, the jazz corner is yours tonight. No rush, no audience — just vinyl ghosts and quiet courage.',
      'Slide into the booth. The ice is melting slowly and so should your shoulders. Welcome back.',
      'Captain, I dimmed the amber lamps. The blues can carry whatever you cannot say out loud.',
      'Another soul navigates the night shift. Good. The tavern keeps a seat for captains like you.',
      'Captain, the piano sighs in B-flat. Match your breathing to it. The rest will follow.',
      'You look like you could use a musical blind box. Surprise yourself — pick a mood and listen.',
      'Captain, the galaxy outside can wait. In here, time pours like honey.',
      'Late hours, soft trumpet, honest silence between songs. Stay awhile.',
      'Captain, welcome to the galactic tavern. Your tab is courage; your change is calm.',
      'The smoke is metaphorical, the warmth is real. Tell the day goodbye at the door.',
      'Captain, I have seen a thousand captains pass through. You belong in this quiet corner.',
      'Let the bass walk while your mind settles. No questions tonight — only accompaniment.',
      'Captain, the night bartender is on duty. What you need is already in the glass.',
      'Old jazz, new focus. The universe spins; we do not have to.',
      'Captain, pull up a stool. The cosmos is loud; this channel is not.',
      'Your secret booth is ready. The playlist knows when to speak and when to hush.',
      'Captain, the tavern lights flicker like distant stars. Good company for deep work.',
      'Last round for worry. First round for clarity. Welcome home, Captain.',
    ],
    zh: [
      '艦長，從寒夜裡進來吧。酒吧很暖，燈光很低，第一個音符已在等你。',
      '嘿，老朋友。外面很折腾？挂在衣帽架上吧。我给你倒了点 smooth 的东西。',
      '艦長，今晚爵士角落属于你。不赶时间，没有观众——只有黑胶幽灵与 quiet 的勇气。',
      '滑进卡座。冰块慢慢化，你的肩膀也该慢慢松。欢迎回来。',
      '艦長，我把琥珀灯调暗了。蓝调能承载你说不出口的一切。',
      '又一个灵魂在夜班航行。很好。酒馆为这样的舰长留着座位。',
      '艦長，钢琴在降 B  sigh。跟着它呼吸。其余会跟上。',
      '你看起来需要一杯音乐盲盒。给自己一个惊喜——选个 mood，听下去。',
      '艦長，外面的银河可以等。在这里，时间像蜂蜜一样流。',
      '深夜、柔 trumpet、歌曲之间 honest 的安静。多待一会儿。',
      '艦長，欢迎光临银河酒场。你的账单是勇气；找零是 calm。',
      '烟是隐喻，暖是真的。把白天留在门口说再见。',
      '艦長，我见过上千位舰长经过。你属于这个 quiet 角落。',
      '让 bass 走步，你的思绪 settle。今晚不提问——只有伴奏。',
      '艦長，深夜调酒师在岗。你需要的已经在杯里。',
      '老爵士，新专注。宇宙在转；我们不必跟着转。',
      '艦長，拉把凳子。宇宙很吵；这个频道不吵。',
      '你的秘密卡座准备好了。歌单知道何时开口、何时安静。',
      '艦長，酒馆灯光像 distant 星星闪烁。深度工作的好同伴。',
      '担忧的最后一杯；清晰的第一杯。欢迎回家，艦長。',
    ],
  },
  'galactic-classical': {
    en: [
      'Captain, good evening. The Nordic cabin is prepared — glass walls, soft piano, zero clutter.',
      'Your digital secretary reporting: schedule cleared, distractions archived. You may begin.',
      'Captain, classical frequencies tuned for productivity. Posture straight, mind lighter.',
      'The room is minimal; the intention is not. Welcome to refined focus.',
      'Captain, I warmed the lights and cooled the noise. Your workspace awaits.',
      'Elegance is efficiency tonight. One task at a time, executed with care.',
      'Captain, the glass cabin overlooks quiet pines. Let the piano mark your pace.',
      'All notifications deferred. Only presence is on the agenda.',
      'Captain, your private office in orbit is ready. Shall we commence?',
      'Precision without pressure — that is the classical method. Begin when ready.',
      'Captain, the secretary channel is calm and crisp. State your intention silently; I will keep time.',
      'Soft keys, sharp mind. The galactic classical suite is now open.',
      'Captain, clutter removed from desk and horizon. Proceed with grace.',
      'A brief inhale, a long exhale, a clean start. You are cleared for excellence.',
      'Captain, productivity is not hustle tonight — it is harmony.',
      'The metronome is invisible; the rhythm is yours. Welcome back.',
      'Captain, I have aligned the ambient light with your focus cycle. Optimal.',
      'Private, polished, peaceful. Three words for your next hour.',
      'Captain, classical mode engaged. Let each note hold the door closed on chaos.',
      'Your cabin, your tempo, your command. Good evening, Captain.',
    ],
    zh: [
      '艦長，晚安。北歐玻璃屋已備妥——透明牆、柔和鋼琴、零雜物。',
      '私人數位秘書報到：行程已清空，干擾已歸檔。可以開始了。',
      '艦長，古典頻率已為生產力調諧。姿態挺直，思緒更輕。',
      '房間極簡；意圖不然。歡迎來到 refined 的專注。',
      '艦長，我暖了燈、冷了噪音。你的工作空間在等你。',
      '今晚優雅即效率。一次一件事，認真完成。',
      '艦長，玻璃屋俯瞰 quiet 松林。讓鋼琴標記你的節奏。',
      '所有通知已延後。议程上只剩「在场」。',
      '艦長，你軌道上的私人辦公室已就緒。要開始了嗎？',
      '精準而不施压——这是古典方法。准备好了就开始。',
      '艦長，秘書頻道 calm 而 crisp。 silently 定下意图；我来计时。',
      '柔键，锐思。银河古典套间现已开放。',
      '艦長，桌面与 horizon 的 clutter 已清除。grace 地继续。',
      '短吸、长呼、干净开始。你已获准 excellence。',
      '艦長，今晚生产力不是 hustle——是和谐。',
      '节拍器 invisible；节奏是你的。欢迎回来。',
      '艦長，我已把环境光与你的专注周期对齐。最佳。',
      '私密、 polished、 peaceful。给你下一小时的三个词。',
      '艦長，古典模式启动。让每个音符把 chaos 关在门外。',
      '你的 cabin、你的 tempo、你的 command。晚安，艦長。',
    ],
  },
  'retro-earth': {
    en: [
      'Captain, time jump successful! We landed at a alpine campfire — stars above, crackling wood below.',
      'Hey! The tent is warm and the playlist smells like nostalgia. Ready for an adventure in focus?',
      'Captain, retro Earth welcomes you back. Leave the future at the zipper; keep the moment.',
      'Snow peaks, orange embers, old songs on a tiny radio. Perfect camp for deep work.',
      'Captain, the explorer channel is live. Today’s mission: one beautiful task by firelight.',
      'You made it through the portal. Boots off, mind on. The night hike continues indoors.',
      'Captain, campfire protocol: tell one worry to the flames, then open your notebook.',
      'The mountains do not rush; neither do we. Welcome to retro calm.',
      'Captain, I unpacked the good vibes and the steady tempo. Your campsite is ready.',
      'Vintage Earth audio online — cassette warmth without the hiss. Settle in.',
      'Captain, constellations look closer up here. So does your goal. Begin the climb.',
      'Adventure mode soft, focus mode strong. The tent flaps; you stay centered.',
      'Captain, the fire pops like applause for showing up. That is enough to start.',
      'Old world comfort, new world clarity. The retro frequency is yours.',
      'Captain, explorer log: location idyllic, spirits high, distractions low. Proceed.',
      'The trail ends at this desk. The view does not. Welcome back, Captain.',
      'Captain, nostalgia is fuel tonight — burn it gently and get things done.',
      'Lantern low, ambition steady. Retro Earth salutes its captain.',
      'Captain, the campfire broadcast is tuned to courage and completion. Stay awhile.',
      'Time travel complete. You are home in the past’s best mood. Let’s work.',
    ],
    zh: [
      '艦長，時空跳躍成功！我们降落在阿尔卑斯篝火旁——头顶星辰，脚下柴裂。',
      '嘿！帐篷很暖，歌单闻起来像 nostalgia。准备好来一场专注冒险了吗？',
      '艦長，復古地球欢迎回来。把未来留在拉链外；留住此刻。',
      '雪峰、橙红火苗、小收音机里的老歌。深度工作的完美营地。',
      '艦長，探險家頻道上線。今日任務：在火光里完成一件 beautiful 的事。',
      '你穿过了 portal。脱靴、上心。夜 hike 在舱内继续。',
      '艦長，篝火协议：把一个 worry 告诉火焰，然后打开笔记本。',
      '山不匆忙；我们也不。欢迎来到 retro calm。',
      '艦長，我 unpack 了 good vibes 与 steady tempo。你的营地准备好了。',
      '復古地球音頻上線——卡帶溫暖，沒有雜音。安頓下來。',
      '艦長，星座在这里看起来更近了。你的目标也是。开始攀登吧。',
      '冒險模式 soft，專注模式 strong。帐篷 flap；你 stay centered。',
      '艦長，火苗 pop 像為你的到來鼓掌。那就足夠開始了。',
      '舊世界 comfort，新世界 clarity。復古頻率属于你。',
      '艦長，探險日誌：位置 idyllic、士气 high、干扰 low。继续。',
      '小徑終於這張桌前。view 没有。欢迎回来，艦長。',
      '艦長，今晚 nostalgia 是燃料——轻轻 burn，把事情做完。',
      '燈籠低、ambition steady。復古地球向舰长致敬。',
      '艦長，篝火廣播已調至 courage 與 completion。多待一會兒。',
      '時空旅行完成。你回到了过去最好的 mood。开工吧。',
    ],
  },
}

export function resolveDjPresetLocale(locale: Language): DjPresetLocale {
  if (locale === 'zh-TW' || locale === 'zh-CN') return 'zh'
  return 'en'
}

export function pickRandomPresetLine(moodId: MusicMoodId, locale: Language): string {
  const presetLocale = resolveDjPresetLocale(locale)
  const lines = DJ_PRESET_LINES[moodId][presetLocale]
  const index = Math.floor(Math.random() * lines.length)
  return lines[index] ?? lines[0] ?? ''
}
